---
- name: Backup Mikrotik Configuration
  hosts: mikrotik
  gather_facts: no

  vars:
    backup_path: "/home/ansible/mikrotik_backups"
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

  tasks:

    - name: Export Mikrotik config
      ansible.builtin.shell: "/export terse"
      register: export_output

    - name: Ensure backup folder exists on host
      ansible.builtin.file:
        path: "{{ backup_path }}"
        state: directory
      delegate_to: localhost

    - name: Save exported config on host
      ansible.builtin.copy:
        content: "{{ export_output.stdout }}"
        dest: "{{ backup_path }}/{{ inventory_hostname }}-{{ timestamp }}.rsc"
      delegate_to: localhost
